// Auto-generated by scripts/gen_extensions.py

mod avi;
mod fonts;
mod matroska;
mod media;
mod mp4;
mod subs;

use phf::Set;

/// A set of file type extensions, stored as byte slices (`&[u8]`).
pub struct Extensions {
    pub avi: &'static Set<&'static [u8]>,
    pub fonts: &'static Set<&'static [u8]>,
    pub matroska: &'static Set<&'static [u8]>,
    pub media: &'static Set<&'static [u8]>,
    pub mp4: &'static Set<&'static [u8]>,
    pub subs: &'static Set<&'static [u8]>,
}

/// A static collection of file type extensions, grouped by type.
/// All extensions are stored as byte slices (`&[u8]`).
pub static EXTENSIONS: Extensions = Extensions {
    avi: &avi::AVI,
    fonts: &fonts::FONTS,
    matroska: &matroska::MATROSKA,
    media: &media::MEDIA,
    mp4: &mp4::MP4,
    subs: &subs::SUBS,
};
