[package]
name = "mux-media"
version = "0.16.5"
authors = ["Ivan Reutov <nujievik@gmail.com>"]
edition = "2024"
rust-version = "1.85"
description = "A CLI utility to mux (merge) video, audio, and subtitles."
repository = "https://github.com/nujievik/mux-media"
license = "MIT OR Apache-2.0"
keywords = ["cli", "utility"]
categories = ["command-line-utilities", "multimedia"]

include = [
    "Cargo.toml",
    "Dockerfile*",
    "README.md",
    "src/**",
]

[features]
default = []
ffmpeg-static = ["ffmpeg-next/static"]
ffmpeg-build = ["ffmpeg-static", "ffmpeg-next/build"]

[dependencies.ffmpeg-next]
version = "=8.1.0"
default-features = false
features = ["codec", "format"]

[dependencies]
chardet = "0.2"
clap = "4"
encoding_rs = "0.8"
encoding_rs_io = "0.1"
enum-map = "2"
globset = "0.4"
is_default = "0.1.4"
lazy-regex = "3"
log = "0.4"
matroska = "0.30"
rayon = "1"
rsubs-lib = "0.3.4"
serde_json = "1"
strum = "0.27"
strum_macros = "0.27"
time = "0.3"
walkdir = "2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winnls"] }

[target.'cfg(unix)'.dependencies]
supports-color = "3"

[dev-dependencies]
phf = { version = "0.13", features = ["macros"] }
rand = "0.9"
