// Auto-generated by scripts/gen_extensions.py

pub static FONTS: phf::Set<&'static [u8]> = phf::phf_set! {
    b"OTF",
    b"OTf",
    b"OtF",
    b"Otf",
    b"oTF",
    b"oTf",
    b"otF",
    b"otf",
    b"TTF",
    b"TTf",
    b"TtF",
    b"Ttf",
    b"tTF",
    b"tTf",
    b"ttF",
    b"ttf",
};
