// Auto-generated by scripts/gen_extensions.py

pub static WEBM: phf::Set<&[u8]> = phf::phf_set! {
    b"WEBM",
    b"WEBm",
    b"WEbM",
    b"WEbm",
    b"WeBM",
    b"WeBm",
    b"WebM",
    b"Webm",
    b"wEBM",
    b"wEBm",
    b"wEbM",
    b"wEbm",
    b"weBM",
    b"weBm",
    b"webM",
    b"webm",
};
