use super::{Blocks, val_parsers::ChaptersParser};
use crate::{
    AudioTracks, ButtonTracks, DefaultTFlags, EnabledTFlags, FontAttachs, ForcedTFlags, Msg,
    MuxConfigArg, OtherAttachs, ParseableArg, Specials, SubTracks, TrackLangs, TrackNames,
    VideoTracks,
};
use clap::{Arg, ArgAction, builder::ValueParser};
use std::str::FromStr;

impl Blocks {
    pub fn target(mut self) -> Self {
        self.0 = self
            .0
            .next_help_heading(Msg::HelpTargetOptions.to_str_localized())
            .arg(
                Arg::new(MuxConfigArg::TargetHelp.undashed())
                    .long(MuxConfigArg::TargetHelp.undashed())
                    .help(Msg::HelpTargetHelp.to_str_localized())
                    .action(ArgAction::SetTrue),
            )
            .arg(
                Arg::new(MuxConfigArg::ListTargets.undashed())
                    .long(MuxConfigArg::ListTargets.undashed())
                    .help(Msg::HelpListTargets.to_str_localized())
                    .action(ArgAction::SetTrue),
            )
            .arg(
                Arg::new(MuxConfigArg::Audio.undashed())
                    .short('a')
                    .long(MuxConfigArg::Audio.undashed())
                    .aliases(&["audio-tracks", "atracks"])
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpAudio.to_str_localized())
                    .value_parser(ValueParser::new(AudioTracks::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoAudio.undashed())
                    .short('A')
                    .long(MuxConfigArg::NoAudio.undashed())
                    .alias("noaudio")
                    .help(Msg::HelpNoAudio.to_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Audio.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Subs.undashed())
                    .short('s')
                    .long(MuxConfigArg::Subs.undashed())
                    .aliases(&["subtitle-tracks", "subtitles", "sub-tracks", "stracks"])
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpSubs.to_str_localized())
                    .value_parser(ValueParser::new(SubTracks::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoSubs.undashed())
                    .short('S')
                    .long(MuxConfigArg::NoSubs.undashed())
                    .aliases(&["no-subtitles", "nosubtitles", "nosubs"])
                    .help(Msg::HelpNoSubs.to_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Subs.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Video.undashed())
                    .short('d')
                    .long(MuxConfigArg::Video.undashed())
                    .aliases(&["video-tracks", "vtracks"])
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpVideo.to_str_localized())
                    .value_parser(ValueParser::new(VideoTracks::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoVideo.undashed())
                    .short('D')
                    .long(MuxConfigArg::NoVideo.undashed())
                    .alias("novideo")
                    .help(Msg::HelpNoVideo.to_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Video.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Buttons.undashed())
                    .short('b')
                    .long(MuxConfigArg::Buttons.undashed())
                    .aliases(&["button-tracks", "btracks"])
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpButtons.to_str_localized())
                    .value_parser(ValueParser::new(ButtonTracks::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoButtons.undashed())
                    .short('B')
                    .long(MuxConfigArg::NoButtons.undashed())
                    .alias("nobuttons")
                    .help(Msg::HelpNoButtons.to_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Buttons.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Chapters.undashed())
                    .short('c')
                    .long(MuxConfigArg::Chapters.undashed())
                    .value_name("file")
                    .help(Msg::HelpChapters.to_str_localized())
                    .value_parser(ValueParser::new(ChaptersParser)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoChapters.undashed())
                    .short('C')
                    .long(MuxConfigArg::NoChapters.undashed())
                    .help(Msg::HelpNoChapters.to_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Chapters.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Fonts.undashed())
                    .short('f')
                    .long(MuxConfigArg::Fonts.undashed())
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpFonts.to_str_localized())
                    .value_parser(ValueParser::new(FontAttachs::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoFonts.undashed())
                    .short('F')
                    .long(MuxConfigArg::NoFonts.undashed())
                    .alias("nofonts")
                    .help(Msg::HelpNoFonts.to_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Fonts.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Attachs.undashed())
                    .short('m')
                    .long(MuxConfigArg::Attachs.undashed())
                    .alias("attachments")
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpAttachs.to_str_localized())
                    .value_parser(ValueParser::new(OtherAttachs::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoAttachs.undashed())
                    .short('M')
                    .long(MuxConfigArg::NoAttachs.undashed())
                    .aliases(&["no-attachments", "noattachments", "noattachs"])
                    .help(Msg::HelpNoAttachs.to_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Attachs.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Defaults.undashed())
                    .long(MuxConfigArg::Defaults.undashed())
                    .aliases(&["default-track-flags", "default-tracks"])
                    .value_name("[n:]B[,m:B]...")
                    .help(Msg::HelpDefaults.to_str_localized())
                    .value_parser(ValueParser::new(DefaultTFlags::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::MaxDefaults.undashed())
                    .long(MuxConfigArg::MaxDefaults.undashed())
                    .value_name("n")
                    .help(Msg::HelpMaxDefaults.to_str_localized())
                    .value_parser(clap::value_parser!(u64)),
            )
            .arg(
                Arg::new(MuxConfigArg::Forceds.undashed())
                    .long(MuxConfigArg::Forceds.undashed())
                    .aliases(&["forced-display-flags", "forced-tracks"])
                    .value_name("[n:]B[,m:B]...")
                    .help(Msg::HelpForceds.to_str_localized())
                    .value_parser(ValueParser::new(ForcedTFlags::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::MaxForceds.undashed())
                    .long(MuxConfigArg::MaxForceds.undashed())
                    .value_name("n")
                    .help(Msg::HelpMaxForceds.to_str_localized())
                    .value_parser(clap::value_parser!(u64)),
            )
            .arg(
                Arg::new(MuxConfigArg::Enableds.undashed())
                    .long(MuxConfigArg::Enableds.undashed())
                    .alias("track-enabled-flags")
                    .value_name("[n:]B[,m:B]...")
                    .help(Msg::HelpEnableds.to_str_localized())
                    .value_parser(ValueParser::new(EnabledTFlags::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::MaxEnableds.undashed())
                    .long(MuxConfigArg::MaxEnableds.undashed())
                    .value_name("n")
                    .help(Msg::HelpMaxEnableds.to_str_localized())
                    .value_parser(clap::value_parser!(u64)),
            )
            .arg(
                Arg::new(MuxConfigArg::Names.undashed())
                    .long(MuxConfigArg::Names.undashed())
                    .alias("track-names")
                    .value_name("[n:]N[,m:N]...")
                    .help(Msg::HelpNames.to_str_localized())
                    .value_parser(ValueParser::new(TrackNames::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::Langs.undashed())
                    .long(MuxConfigArg::Langs.undashed())
                    .alias("languages")
                    .value_name("[n:]L[,m:L]...")
                    .help(Msg::HelpLangs.to_str_localized())
                    .value_parser(ValueParser::new(TrackLangs::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::Specials.undashed())
                    .long(MuxConfigArg::Specials.undashed())
                    .value_name("\"n[ m]...\"")
                    .allow_hyphen_values(true)
                    .help(Msg::HelpSpecials.to_str_localized())
                    .value_parser(ValueParser::new(Specials::from_str)),
            );

        self
    }
}
