use super::{Blocks, val_parsers::ChaptersParser};
use crate::{
    AudioTracks, DefaultTrackFlags, EnabledTrackFlags, FontAttachs, ForcedTrackFlags, Msg,
    MuxConfigArg, OtherAttachs, ParseableArg, Specials, SubTracks, TrackLangs, TrackNames,
    VideoTracks,
};
use clap::{Arg, ArgAction, builder::ValueParser};
use std::str::FromStr;

impl Blocks {
    pub fn target(mut self) -> Self {
        self.0 = self
            .0
            .next_help_heading(Msg::HelpTargetOptions.as_str_localized())
            .arg(
                Arg::new(MuxConfigArg::Target.undashed())
                    .short('t')
                    .long(MuxConfigArg::Target.undashed())
                    .value_name("trg")
                    .help(Msg::HelpTargetHelp.as_str_localized())
                    .trailing_var_arg(true)
                    .allow_hyphen_values(true)
                    .num_args(1..),
            )
            .arg(
                Arg::new(MuxConfigArg::ListTargets.undashed())
                    .long(MuxConfigArg::ListTargets.undashed())
                    .help(Msg::HelpListTargets.as_str_localized())
                    .action(ArgAction::SetTrue),
            )
            .arg(
                Arg::new(MuxConfigArg::Audio.undashed())
                    .short('a')
                    .long(MuxConfigArg::Audio.undashed())
                    .aliases(&["audio-tracks", "atracks"])
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpAudio.as_str_localized())
                    .value_parser(ValueParser::new(AudioTracks::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoAudio.undashed())
                    .short('A')
                    .long(MuxConfigArg::NoAudio.undashed())
                    .alias("noaudio")
                    .help(Msg::HelpNoAudio.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Audio.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Subs.undashed())
                    .short('s')
                    .long(MuxConfigArg::Subs.undashed())
                    .aliases(&["subtitle-tracks", "subtitles", "sub-tracks", "stracks"])
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpSubs.as_str_localized())
                    .value_parser(ValueParser::new(SubTracks::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoSubs.undashed())
                    .short('S')
                    .long(MuxConfigArg::NoSubs.undashed())
                    .aliases(&["no-subtitles", "nosubtitles", "nosubs"])
                    .help(Msg::HelpNoSubs.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Subs.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Video.undashed())
                    .short('d')
                    .long(MuxConfigArg::Video.undashed())
                    .aliases(&["video-tracks", "vtracks"])
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpVideo.as_str_localized())
                    .value_parser(ValueParser::new(VideoTracks::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoVideo.undashed())
                    .short('D')
                    .long(MuxConfigArg::NoVideo.undashed())
                    .alias("novideo")
                    .help(Msg::HelpNoVideo.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Video.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Chapters.undashed())
                    .short('c')
                    .long(MuxConfigArg::Chapters.undashed())
                    .value_name("file")
                    .help(Msg::HelpChapters.as_str_localized())
                    .value_parser(ValueParser::new(ChaptersParser)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoChapters.undashed())
                    .short('C')
                    .long(MuxConfigArg::NoChapters.undashed())
                    .help(Msg::HelpNoChapters.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Chapters.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Fonts.undashed())
                    .short('f')
                    .long(MuxConfigArg::Fonts.undashed())
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpFonts.as_str_localized())
                    .value_parser(ValueParser::new(FontAttachs::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoFonts.undashed())
                    .short('F')
                    .long(MuxConfigArg::NoFonts.undashed())
                    .alias("nofonts")
                    .help(Msg::HelpNoFonts.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Fonts.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Attachs.undashed())
                    .short('m')
                    .long(MuxConfigArg::Attachs.undashed())
                    .alias("attachments")
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpAttachs.as_str_localized())
                    .value_parser(ValueParser::new(OtherAttachs::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::NoAttachs.undashed())
                    .short('M')
                    .long(MuxConfigArg::NoAttachs.undashed())
                    .aliases(&["no-attachments", "noattachments", "noattachs"])
                    .help(Msg::HelpNoAttachs.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(MuxConfigArg::Attachs.undashed()),
            )
            .arg(
                Arg::new(MuxConfigArg::Defaults.undashed())
                    .long(MuxConfigArg::Defaults.undashed())
                    .aliases(&["default-track-flags", "default-tracks"])
                    .value_name("[n:]B[,m:B]...")
                    .help(Msg::HelpDefaults.as_str_localized())
                    .value_parser(ValueParser::new(DefaultTrackFlags::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::MaxDefaults.undashed())
                    .long(MuxConfigArg::MaxDefaults.undashed())
                    .value_name("n")
                    .help(Msg::HelpMaxDefaults.as_str_localized())
                    .value_parser(clap::value_parser!(u64)),
            )
            .arg(
                Arg::new(MuxConfigArg::Forceds.undashed())
                    .long(MuxConfigArg::Forceds.undashed())
                    .aliases(&["forced-display-flags", "forced-tracks"])
                    .value_name("[n:]B[,m:B]...")
                    .help(Msg::HelpForceds.as_str_localized())
                    .value_parser(ValueParser::new(ForcedTrackFlags::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::MaxForceds.undashed())
                    .long(MuxConfigArg::MaxForceds.undashed())
                    .value_name("n")
                    .help(Msg::HelpMaxForceds.as_str_localized())
                    .value_parser(clap::value_parser!(u64)),
            )
            .arg(
                Arg::new(MuxConfigArg::Enableds.undashed())
                    .long(MuxConfigArg::Enableds.undashed())
                    .alias("track-enabled-flags")
                    .value_name("[n:]B[,m:B]...")
                    .help(Msg::HelpEnableds.as_str_localized())
                    .value_parser(ValueParser::new(EnabledTrackFlags::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::MaxEnableds.undashed())
                    .long(MuxConfigArg::MaxEnableds.undashed())
                    .value_name("n")
                    .help(Msg::HelpMaxEnableds.as_str_localized())
                    .value_parser(clap::value_parser!(u64)),
            )
            .arg(
                Arg::new(MuxConfigArg::Names.undashed())
                    .long(MuxConfigArg::Names.undashed())
                    .alias("track-names")
                    .value_name("[n:]N[,m:N]...")
                    .help(Msg::HelpNames.as_str_localized())
                    .value_parser(ValueParser::new(TrackNames::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::Langs.undashed())
                    .long(MuxConfigArg::Langs.undashed())
                    .alias("languages")
                    .value_name("[n:]L[,m:L]...")
                    .help(Msg::HelpLangs.as_str_localized())
                    .value_parser(ValueParser::new(TrackLangs::from_str)),
            )
            .arg(
                Arg::new(MuxConfigArg::Specials.undashed())
                    .long(MuxConfigArg::Specials.undashed())
                    .value_name("\"n[ m]...\"")
                    .allow_hyphen_values(true)
                    .help(Msg::HelpSpecials.as_str_localized())
                    .value_parser(ValueParser::new(Specials::from_str)),
            );

        self
    }
}
