use super::{Blocks, val_parsers::ChaptersParser};
use crate::{
    AudioTracks, DefaultTrackFlags, EnabledTrackFlags, FontAttachs, ForcedTrackFlags, Msg,
    OtherAttachs, Raws, SubTracks, TrackLangs, TrackNames, VideoTracks, undashed,
};
use clap::{Arg, ArgAction, builder::ValueParser};
use std::str::FromStr;

impl Blocks {
    pub fn target(mut self) -> Self {
        self.0 = self
            .0
            .next_help_heading(Msg::HelpTargetOptions.as_str_localized())
            .arg(
                Arg::new(undashed!(Target))
                    .short('t')
                    .long(undashed!(Target))
                    .value_name("trg")
                    .help(Msg::HelpTargetHelp.as_str_localized())
                    .trailing_var_arg(true)
                    .allow_hyphen_values(true)
                    .num_args(1..),
            )
            .arg(
                Arg::new(undashed!(ListTargets))
                    .long(undashed!(ListTargets))
                    .help(Msg::HelpListTargets.as_str_localized())
                    .action(ArgAction::SetTrue),
            )
            .arg(
                Arg::new(undashed!(Audio))
                    .short('a')
                    .long(undashed!(Audio))
                    .alias(undashed!(AudioTracks))
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpAudio.as_str_localized())
                    .value_parser(ValueParser::new(AudioTracks::from_str)),
            )
            .arg(
                Arg::new(undashed!(NoAudio))
                    .short('A')
                    .long(undashed!(NoAudio))
                    .help(Msg::HelpNoAudio.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(undashed!(Audio)),
            )
            .arg(
                Arg::new(undashed!(Subs))
                    .short('s')
                    .long(undashed!(Subs))
                    .alias(undashed!(SubtitleTracks))
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpSubs.as_str_localized())
                    .value_parser(ValueParser::new(SubTracks::from_str)),
            )
            .arg(
                Arg::new(undashed!(NoSubs))
                    .short('S')
                    .long(undashed!(NoSubs))
                    .alias(undashed!(NoSubtitles))
                    .help(Msg::HelpNoSubs.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(undashed!(Subs)),
            )
            .arg(
                Arg::new(undashed!(Video))
                    .short('d')
                    .long(undashed!(Video))
                    .alias(undashed!(VideoTracks))
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpVideo.as_str_localized())
                    .value_parser(ValueParser::new(VideoTracks::from_str)),
            )
            .arg(
                Arg::new(undashed!(NoVideo))
                    .short('D')
                    .long(undashed!(NoVideo))
                    .help(Msg::HelpNoVideo.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(undashed!(Video)),
            )
            .arg(
                Arg::new(undashed!(Chapters))
                    .short('c')
                    .long(undashed!(Chapters))
                    .value_name("file")
                    .help(Msg::HelpChapters.as_str_localized())
                    .value_parser(ValueParser::new(ChaptersParser)),
            )
            .arg(
                Arg::new(undashed!(NoChapters))
                    .short('C')
                    .long(undashed!(NoChapters))
                    .help(Msg::HelpNoChapters.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(undashed!(Chapters)),
            )
            .arg(
                Arg::new(undashed!(Fonts))
                    .short('f')
                    .long(undashed!(Fonts))
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpFonts.as_str_localized())
                    .value_parser(ValueParser::new(FontAttachs::from_str)),
            )
            .arg(
                Arg::new(undashed!(NoFonts))
                    .short('F')
                    .long(undashed!(NoFonts))
                    .help(Msg::HelpNoFonts.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(undashed!(Fonts)),
            )
            .arg(
                Arg::new(undashed!(Attachs))
                    .short('m')
                    .long(undashed!(Attachs))
                    .alias(undashed!(Attachments))
                    .value_name("[!]n[,m]...")
                    .help(Msg::HelpAttachs.as_str_localized())
                    .value_parser(ValueParser::new(OtherAttachs::from_str)),
            )
            .arg(
                Arg::new(undashed!(NoAttachs))
                    .short('M')
                    .long(undashed!(NoAttachs))
                    .alias(undashed!(NoAttachments))
                    .help(Msg::HelpNoAttachs.as_str_localized())
                    .action(ArgAction::SetTrue)
                    .conflicts_with(undashed!(Attachs)),
            )
            .arg(
                Arg::new(undashed!(Defaults))
                    .long(undashed!(Defaults))
                    .value_name("[n:]B[,m:B]...")
                    .help(Msg::HelpDefaults.as_str_localized())
                    .value_parser(ValueParser::new(DefaultTrackFlags::from_str)),
            )
            .arg(
                Arg::new(undashed!(MaxDefaults))
                    .long(undashed!(MaxDefaults))
                    .value_name("n")
                    .help(Msg::HelpMaxDefaults.as_str_localized())
                    .value_parser(clap::value_parser!(u64)),
            )
            .arg(
                Arg::new(undashed!(Forceds))
                    .long(undashed!(Forceds))
                    .value_name("[n:]B[,m:B]...")
                    .help(Msg::HelpForceds.as_str_localized())
                    .value_parser(ValueParser::new(ForcedTrackFlags::from_str)),
            )
            .arg(
                Arg::new(undashed!(MaxForceds))
                    .long(undashed!(MaxForceds))
                    .value_name("n")
                    .help(Msg::HelpMaxForceds.as_str_localized())
                    .value_parser(clap::value_parser!(u64)),
            )
            .arg(
                Arg::new(undashed!(Enableds))
                    .long(undashed!(Enableds))
                    .value_name("[n:]B[,m:B]...")
                    .help(Msg::HelpEnableds.as_str_localized())
                    .value_parser(ValueParser::new(EnabledTrackFlags::from_str)),
            )
            .arg(
                Arg::new(undashed!(MaxEnableds))
                    .long(undashed!(MaxEnableds))
                    .value_name("n")
                    .help(Msg::HelpMaxEnableds.as_str_localized())
                    .value_parser(clap::value_parser!(u64)),
            )
            .arg(
                Arg::new(undashed!(Names))
                    .long(undashed!(Names))
                    .value_name("[n:]N[,m:N]...")
                    .help(Msg::HelpNames.as_str_localized())
                    .value_parser(ValueParser::new(TrackNames::from_str)),
            )
            .arg(
                Arg::new(undashed!(Langs))
                    .long(undashed!(Langs))
                    .value_name("[n:]L[,m:L]...")
                    .help(Msg::HelpLangs.as_str_localized())
                    .value_parser(ValueParser::new(TrackLangs::from_str)),
            )
            .arg(
                Arg::new(undashed!(Raws))
                    .long(undashed!(Raws))
                    .value_name("\"n[ m]...\"")
                    .allow_hyphen_values(true)
                    .help(Msg::HelpRaws.as_str_localized())
                    .value_parser(ValueParser::new(Raws::from_str)),
            );

        self
    }
}
