use mux_media::*;

#[test]
fn test_ok_exit() {
    ["--list-targets", "--list-containers", "--list-langs"]
        .iter()
        .for_each(|arg| {
            let err = match MuxConfig::try_from_args([arg]) {
                Ok(_) => panic!("Unexpected ok"),
                Err(e) => e,
            };
            assert_eq!(0, err.code);
            assert_eq!(MuxErrorKind::Ok, err.kind);
        })
}

crate::build_test_parseable_args!(
    test_parseable_args, MuxConfig;
    Input => "input",
    Output => "output",
    Range => "range",
    Skip => "skip",
    Depth => "depth",
    Solo => "solo",
    Locale => "locale",
    Verbose => "verbose",
    Quiet => "quiet",
    ExitOnErr => "exit-on-err",
    Json => "json",
    Load => "load",
    Reencode => "reencode",
    Pro => "pro",
    HelpAutoDefaults => "auto-defaults / --no-auto-defaults",
    AutoDefaults => "auto-defaults",
    NoAutoDefaults => "no-auto-defaults",
    HelpAutoForceds => "auto-forceds / --no-auto-forceds",
    AutoForceds => "auto-forceds",
    NoAutoForceds => "no-auto-forceds",
    HelpAutoEnableds => "auto-enableds / --no-auto-enableds",
    AutoEnableds => "auto-enableds",
    NoAutoEnableds => "no-auto-enableds",
    HelpAutoNames => "auto-names / --no-auto-names",
    AutoNames => "auto-names",
    NoAutoNames => "no-auto-names",
    HelpAutoLangs => "auto-langs / --no-auto-langs",
    AutoLangs => "auto-langs",
    NoAutoLangs => "no-auto-langs",
    HelpAutoCharsets => "auto-charsets / --no-auto-charsets",
    AutoCharsets => "auto-charsets",
    NoAutoCharsets => "no-auto-charsets",
    Target => "target",
    TargetHelp => "target <trg> [options]",
    ListTargets => "list-targets",
    Audio => "audio",
    AudioTracks => "audio-tracks",
    NoAudio => "no-audio",
    Subs => "subs",
    SubtitleTracks => "subtitle-tracks",
    NoSubs => "no-subs",
    NoSubtitles => "no-subtitles",
    Video => "video",
    VideoTracks => "video-tracks",
    NoVideo => "no-video",
    Buttons => "buttons",
    ButtonTracks => "button-tracks",
    NoButtons => "no-buttons",
    Chapters => "chapters",
    NoChapters => "no-chapters",
    Attachments => "attachments",
    NoAttachments => "no-attachments",
    Fonts => "fonts",
    NoFonts => "no-fonts",
    Attachs => "attachs",
    NoAttachs => "no-attachs",
    DefaultTrackFlag => "default-track-flag",
    Defaults => "defaults",
    MaxDefaults => "max-defaults",
    ForcedDisplayFlag => "forced-display-flag",
    Forceds => "forceds",
    MaxForceds => "max-forceds",
    Enableds => "enableds",
    MaxEnableds => "max-enableds",
    TrackEnabledFlag => "track-enabled-flag",
    Metadata => "metadata",
    Names => "names",
    Title => "title",
    TrackName => "track-name",
    Langs => "langs",
    Language => "language",
    Specials => "specials",
    ListContainers => "list-containers",
    ListLangs => "list-langs",
    UserTools => "user-tools",
    FfmpegHelp => "ffmpeg [options]",
    MkvmergeHelp => "mkvmerge [options]",
    Version => "version",
    Help => "help",
    SubCharset => "sub-charset",
    TrackOrder => "track-order",
);
