name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
        default: 'v1.0.0'

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-x64-build:
    runs-on: macos-latest
    env:
      TARGET: x86_64-apple-darwin
      FFMPEG_DIR: ${{ github.workspace }}/target/x86_64-apple-darwin/mux-media-ffmpeg
      RUSTFLAGS: "-C target-cpu=core2"

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew update
          brew install nasm make

      - name: Build & Install static FFmpeg
        run: |
          SRC_DIR="${{ github.workspace }}/target/ffmpeg-src"
          
          git clone --depth 1 --branch n8.1.2 https://github.com/ffmpeg/ffmpeg $SRC_DIR
          cd $SRC_DIR
          ./configure --arch=x86_64 --target-os=darwin --prefix="${{ env.FFMPEG_DIR }}" \
            --pkg-config-flags="--static" \
            --disable-runtime-cpudetect --disable-autodetect --disable-programs --disable-doc \
            --disable-avdevice --disable-swresample --disable-swscale --disable-avfilter --disable-network \
            --disable-encoders --disable-hwaccels --disable-muxers --disable-protocols --disable-devices --disable-filters \
            --disable-asm --disable-sse4 --disable-sse42 --disable-avx --disable-xop --disable-fma3 --disable-fma4 \
            --disable-avx2 --disable-avx512 --disable-avx512icl --disable-aesni --disable-clmul \
            --disable-shared --enable-static --enable-muxer=matroska --enable-protocol=file --enable-avcodec --enable-avformat --cpu=generic || {
              echo "=== CONFIGURATION FAILED ==="
              cat ffbuild/config.log
              exit 1
            }

            make -j$(sysctl -n hw.ncpu)
            make install

      - name: Build
        run: cargo build --release --features ffmpeg-static --target ${{ env.TARGET }}

      - uses: actions/upload-artifact@v4
        with:
          name: mux-media-macOS-x64
          path: target/release/mux-media
