name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-x64-static:
    runs-on: ubuntu-latest

    env:
      TARGET: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - name: Build & Test
        run: |
          docker build -f dockerfiles/Dockerfile.${{ env.TARGET }} -t builder .
